<?php

declare(strict_types=1);

namespace BitWasp\Test\Trezor\Device;

abstract class TestCase extends \PHPUnit\Framework\TestCase
{
    /**
     * Set during test
     * @var int
     */
    private $emu;

    /**
     * Set during test
     * @var int
     */
    private $bridge;

    public function getRootPath(): string
    {
        return __DIR__ . "/../../";
    }

    public function getEmulatorPath(): string
    {
        return "{$this->getRootPath()}tool/emulator/trezor-mcu/build/trezor-emulator64-master";
    }

    public function getEmulatorStartCommand(): string
    {
        return $this->getEmulatorPath() .
        /* . " > /dev/null"  . */
        " > 1 & echo $! ; ";
    }
    public function getBridgeStartCommand(): string
    {
        return $this->getBridgePath() .
            /* . " > /dev/null"  . */
            " -u=false -e 21324 -l /tmp/trezor-bridge > 1 & echo $! ; ";
    }
    public function getBridgePath(): string
    {
        $gopath = getenv('GOPATH');
        if (!$gopath) {
            throw new \RuntimeException('GOPATH not set');
        }

        return "{$gopath}/bin/trezord-go";
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $bridgeStart = $this->getBridgeStartCommand();
        $emuStart = $this->getEmulatorStartCommand();

        $pidEmu = exec($emuStart);
        usleep( (int) (0.2 * pow(10,6)));

        $pidBridge = exec($bridgeStart);
        usleep( (int) (0.2 * pow(10,6)));

        $this->emu = $pidEmu;
        $this->bridge = $pidBridge;
    }

    public function tearDown()
    {
        exec("kill -9 {$this->emu}");
        exec("kill -9 {$this->bridge}");
    }
}
